pip install numpy
pip install python-dotenv
pip install setuptools
pip install wheel
pip install PyJWT
pip install opencv-python-headless
pip install face-recognition
pip install dlib
pip install python-multipart
pip install psutil
pip install scikit-learn
pip install matplotlib
pip install pandas
